repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
      # Kubernetes configs often have multiple documents
      args: [--allow-multiple-documents]
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.8'
    hooks:
      - id: ruff
