apiVersion: v1
kind: Service
metadata:
  name: fastapi-example-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fastapi-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-example-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-example
  template:
    metadata:
      labels:
        app: fastapi-example
    spec:
      containers:
      - name: fastapi-example
        image: ghcr.io/forumviriumhelsinki/k8s-fastapi:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ghcr-login-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - fastapi-example.dataportal.fi
    secretName: fastapi-example-tls
  rules:
  - host: fastapi-example.dataportal.fi
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: fastapi-example-service
            port:
              number: 80
